include: package:lint/analysis_options.yaml

linter:

  rules:

    always_use_package_imports: true
    avoid_dynamic_calls: true
    comment_references: true
    empty_statements: true
    hash_and_equals: true
    prefer_void_to_null: true
    unnecessary_statements: true
    always_declare_return_types: true
    always_put_control_body_on_new_line: true
    always_put_required_named_parameters_first: true
    avoid_bool_literals_in_conditional_expressions: true
    avoid_classes_with_only_static_members: true
    avoid_redundant_argument_values: true
    avoid_unused_constructor_parameters: true
    directives_ordering: true
    lines_longer_than_80_chars: true
    package_api_docs: true
    public_member_api_docs: true
    type_annotate_public_apis: true

